#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Nov 06 11:25:03 CET 2023
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 4d48539bb5674c329a4888d016be853f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L axi_bram_ctrl_v4_1_4 -L blk_mem_gen_v8_4_4 -L axi_lite_ipif_v3_0_4 -L axi_intc_v4_1_15 -L xlconstant_v1_1_7 -L lib_cdc_v1_0_2 -L proc_sys_reset_v5_0_13 -L smartconnect_v1_0 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_22 -L axi_vip_v1_1_8 -L xlconcat_v2_1_4 -L zynq_ultra_ps_e_vip_v1_0_8 -L uvm -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot u96v2_sbc_mp4d_wrapper_behav xil_defaultlib.u96v2_sbc_mp4d_wrapper xil_defaultlib.glbl -log elaborate.log"
xelab -wto 4d48539bb5674c329a4888d016be853f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L axi_bram_ctrl_v4_1_4 -L blk_mem_gen_v8_4_4 -L axi_lite_ipif_v3_0_4 -L axi_intc_v4_1_15 -L xlconstant_v1_1_7 -L lib_cdc_v1_0_2 -L proc_sys_reset_v5_0_13 -L smartconnect_v1_0 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_22 -L axi_vip_v1_1_8 -L xlconcat_v2_1_4 -L zynq_ultra_ps_e_vip_v1_0_8 -L uvm -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot u96v2_sbc_mp4d_wrapper_behav xil_defaultlib.u96v2_sbc_mp4d_wrapper xil_defaultlib.glbl -log elaborate.log

