#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Nov 06 11:26:16 CET 2023
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim u96v2_sbc_mp4d_wrapper_behav -key {Behavioral:sim_1:Functional:u96v2_sbc_mp4d_wrapper} -tclbatch u96v2_sbc_mp4d_wrapper.tcl -protoinst "protoinst_files/bd_53ee.protoinst" -protoinst "protoinst_files/u96v2_sbc_mp4d.protoinst" -log simulate.log"
xsim u96v2_sbc_mp4d_wrapper_behav -key {Behavioral:sim_1:Functional:u96v2_sbc_mp4d_wrapper} -tclbatch u96v2_sbc_mp4d_wrapper.tcl -protoinst "protoinst_files/bd_53ee.protoinst" -protoinst "protoinst_files/u96v2_sbc_mp4d.protoinst" -log simulate.log

