# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src/u96v2_sbc_mp4d.xdc

# Block Designs: bd/u96v2_sbc_mp4d/u96v2_sbc_mp4d.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_sbc_mp4d || ORIG_REF_NAME==u96v2_sbc_mp4d} -quiet] -quiet

# IP: bd/u96v2_sbc_mp4d/ip/u96v2_sbc_mp4d_axi_bram_ctrl_0_0/u96v2_sbc_mp4d_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_sbc_mp4d_axi_bram_ctrl_0_0 || ORIG_REF_NAME==u96v2_sbc_mp4d_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/u96v2_sbc_mp4d/ip/u96v2_sbc_mp4d_axi_bram_ctrl_0_bram_0/u96v2_sbc_mp4d_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_sbc_mp4d_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==u96v2_sbc_mp4d_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/u96v2_sbc_mp4d/ip/u96v2_sbc_mp4d_axi_intc_0_0/u96v2_sbc_mp4d_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_sbc_mp4d_axi_intc_0_0 || ORIG_REF_NAME==u96v2_sbc_mp4d_axi_intc_0_0} -quiet] -quiet

# IP: bd/u96v2_sbc_mp4d/ip/u96v2_sbc_mp4d_axi_smc_0/u96v2_sbc_mp4d_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_sbc_mp4d_axi_smc_0 || ORIG_REF_NAME==u96v2_sbc_mp4d_axi_smc_0} -quiet] -quiet

# IP: bd/u96v2_sbc_mp4d/ip/u96v2_sbc_mp4d_rst_ps8_0_100M_0/u96v2_sbc_mp4d_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_sbc_mp4d_rst_ps8_0_100M_0 || ORIG_REF_NAME==u96v2_sbc_mp4d_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/u96v2_sbc_mp4d/ip/u96v2_sbc_mp4d_xlconcat_0_0/u96v2_sbc_mp4d_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_sbc_mp4d_xlconcat_0_0 || ORIG_REF_NAME==u96v2_sbc_mp4d_xlconcat_0_0} -quiet] -quiet

# IP: bd/u96v2_sbc_mp4d/ip/u96v2_sbc_mp4d_xlconstant_0_0/u96v2_sbc_mp4d_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_sbc_mp4d_xlconstant_0_0 || ORIG_REF_NAME==u96v2_sbc_mp4d_xlconstant_0_0} -quiet] -quiet

# IP: bd/u96v2_sbc_mp4d/ip/u96v2_sbc_mp4d_zynq_ultra_ps_e_0_0/u96v2_sbc_mp4d_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_sbc_mp4d_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==u96v2_sbc_mp4d_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/u96v2_sbc_mp4d/ip/u96v2_sbc_mp4d_xlconstant_1_0/u96v2_sbc_mp4d_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_sbc_mp4d_xlconstant_1_0 || ORIG_REF_NAME==u96v2_sbc_mp4d_xlconstant_1_0} -quiet] -quiet

# IP: bd/u96v2_sbc_mp4d/ip/u96v2_sbc_mp4d_ImageFilter_0_1/u96v2_sbc_mp4d_ImageFilter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_sbc_mp4d_ImageFilter_0_1 || ORIG_REF_NAME==u96v2_sbc_mp4d_ImageFilter_0_1} -quiet] -quiet

# XDC: /home/michael/MPSoC4Drones/hdl/projects/u96v2_sbc_mp4d_2020_2/u96v2_sbc_mp4d.gen/sources_1/bd/u96v2_sbc_mp4d/u96v2_sbc_mp4d_ooc.xdc
